trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore
  displayName: "Restore"

- script: dotnet build --configuration Release
  displayName: "Build"

- script: dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: "Pack"

- task: NuGetCommand@2
  displayName: "Publish to Azure Artifacts"
  inputs:
    command: push
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    #publishVstsFeed: 'SampleSharedServicesAPIFeed'
    publishVstsFeed: 'd6cc5835-0683-4b38-9a20-10e92fd7b62a'

