trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetAuthenticate@1
  displayName: Authenticate to Azure Artifacts
  inputs:
    nuGetServiceConnections: 'SampleSharedServiceApi_NuGet_ServiceConnection'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
    arguments: '--source https://pkgs.dev.azure.com/jobsmacoro/SampleSharedServicesApi_AzureDevOps/_packaging/SampleSharedServicesAPIFeed/nuget/v3/index.json --source https://api.nuget.org/v3/index.json'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration Release'

- task: CopyFiles@2
  displayName: Copy NuGet package
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/bin/Release'
    Contents: '*.nupkg'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: NuGetCommand@2
  displayName: Publish to Azure Artifacts
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    publishFeedCredentials: 'SampleSharedServiceApi_NuGet_ServiceConnection'
    publishFeedUrl: 'https://pkgs.dev.azure.com/jobsmacoro/SampleSharedServicesApi_AzureDevOps/_packaging/SampleSharedServicesAPIFeed/nuget/v3/index.json'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    #this is shit