trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'windows-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore
  displayName: "Restore"

- script: dotnet build --configuration Release
  displayName: "Build"

- script: dotnet pack --configuration Release /p:PackageVersion=1.0.0
  displayName: "Pack"

- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '**/*.nupkg'
    publishVstsFeed: 'd6cc5835-0683-4b38-9a20-10e92fd7b62a'
  displayName: "Publish to Azure Artifacts"
